const icons = {
  home: require("../assets/icons/home.png"),
  learn: require("../assets/icons/text-box.png"),
  profile: require("../assets/icons/woman.png"),
  settings: require("../assets/icons/settings.png"),
  challenge: require("../assets/icons/challenge.png"),
  eye: require("../assets/icons/eye.png"),
  eyehide: require("../assets/icons/eyehide.png"),
  search: require("../assets/icons/search.png"),
  novice: require("../assets/icons/novice.png"),
  intermediate: require("../assets/icons/intermediate.png"),
  advanced: require("../assets/icons/advanced.png"),
  atom: require("../assets/icons/atom.png"),
  enzyme: require("../assets/icons/enzyme.png"),
  vocabulary: require("../assets/icons/vocabulary.png"),
  winning: require("../assets/icons/winning.png"),
  usericon: require("../assets/icons/usericon.png"),
  envelope: require("../assets/icons/envelope.png"),
  padlock: require("../assets/icons/padlock.png"),
  logout: require("../assets/icons/logout.png"),
  greater: require("../assets/icons/greater.png"),
  maths: require("../assets/icons/function.png"),
  edu: require("../assets/icons/presentation.png"),
  edutech: require("../assets/icons/light-bulb.png"),
};
export default icons;
