export const english = [
  {
    id: 1,
    difficulty: "easy",
    question: "What is the synonym of 'happy'?",
    options: ["Sad", "Joyful", "Angry", "Tired"],
    answer: "Joyful",
  },
  {
    id: 2,
    difficulty: "easy",
    question:
      "Choose the correct form of the verb: 'She _____ to the store yesterday.'",
    options: ["go", "goes", "went", "gone"],
    answer: "went",
  },
  {
    id: 3,
    difficulty: "easy",
    question: "What is the antonym of 'strong'?",
    options: ["Weak", "Brave", "Healthy", "Bold"],
    answer: "Weak",
  },
  {
    id: 4,
    difficulty: "easy",
    question: "Which word is a noun? 'Run', 'Blue', 'Happiness', 'Quickly'",
    options: ["Run", "Blue", "Happiness", "Quickly"],
    answer: "Happiness",
  },
  {
    id: 5,
    difficulty: "easy",
    question: "Fill in the blank: 'He is taller _____ his brother.'",
    options: ["then", "than", "to", "with"],
    answer: "than",
  },
  {
    id: 6,
    difficulty: "easy",
    question: "What is the past tense of 'write'?",
    options: ["written", "wrote", "writing", "writes"],
    answer: "wrote",
  },
  {
    id: 7,
    difficulty: "easy",
    question:
      "Choose the correct spelling: 'accomodate', 'accommodate', 'acommodate', 'acomodate'",
    options: ["accomodate", "accommodate", "acommodate", "acomodate"],
    answer: "accommodate",
  },
  {
    id: 8,
    difficulty: "easy",
    question: "What is the plural of 'mouse'?",
    options: ["mouses", "mice", "mices", "mouse"],
    answer: "mice",
  },
  {
    id: 9,
    difficulty: "easy",
    question:
      "Fill in the blank: 'She is interested _____ learning new languages.'",
    options: ["in", "at", "on", "with"],
    answer: "in",
  },
  {
    id: 10,
    difficulty: "easy",
    question: "Choose the correct word: 'They _____ going to the beach.'",
    options: ["is", "are", "was", "were"],
    answer: "are",
  },
  {
    id: 11,
    difficulty: "easy",
    question: "What is the synonym of 'quick'?",
    options: ["Slow", "Fast", "Lazy", "Dull"],
    answer: "Fast",
  },
  {
    id: 12,
    difficulty: "easy",
    question: "Fill in the blank: 'The book is _____ the table.'",
    options: ["in", "on", "at", "by"],
    answer: "on",
  },
  {
    id: 13,
    difficulty: "easy",
    question: "What is the past tense of 'teach'?",
    options: ["teached", "taught", "teach", "teaching"],
    answer: "taught",
  },
  {
    id: 14,
    difficulty: "easy",
    question: "Choose the correct word: 'The cake tastes _____.'",
    options: ["good", "well", "goodly", "best"],
    answer: "good",
  },
  {
    id: 15,
    difficulty: "easy",
    question: "Fill in the blank: 'He ran _____ fast as he could.'",
    options: ["so", "as", "very", "too"],
    answer: "as",
  },
  {
    id: 16,
    difficulty: "easy",
    question: "What is the antonym of 'hot'?",
    options: ["Warm", "Cold", "Cool", "Tepid"],
    answer: "Cold",
  },
  {
    id: 17,
    difficulty: "easy",
    question: "What is the plural of 'child'?",
    options: ["childs", "children", "childrens", "child"],
    answer: "children",
  },
  {
    id: 18,
    difficulty: "easy",
    question: "Choose the correct word: 'He _____ his homework before dinner.'",
    options: ["do", "does", "did", "done"],
    answer: "did",
  },
  {
    id: 19,
    difficulty: "easy",
    question: "Fill in the blank: 'She is the _____ student in the class.'",
    options: ["best", "better", "good", "well"],
    answer: "best",
  },
  {
    id: 20,
    difficulty: "easy",
    question: "What is the synonym of 'small'?",
    options: ["Tiny", "Huge", "Big", "Large"],
    answer: "Tiny",
  },
  {
    id: 21,
    difficulty: "medium",
    question:
      "Choose the correct word: 'The committee has _____ decision to make.'",
    options: ["its", "it's", "their", "they're"],
    answer: "its",
  },
  {
    id: 22,
    difficulty: "medium",
    question: "What is the correct passive form of 'The chef cooks the meal'?",
    options: [
      "The meal is cooked by the chef",
      "The meal is cooking by the chef",
      "The meal was cooked by the chef",
      "The meal cooked by the chef",
    ],
    answer: "The meal is cooked by the chef",
  },
  {
    id: 23,
    difficulty: "medium",
    question: "Fill in the blank: 'Neither of the answers _____ correct.'",
    options: ["is", "are", "were", "being"],
    answer: "is",
  },
  {
    id: 24,
    difficulty: "medium",
    question: "What is the synonym of 'elaborate'?",
    options: ["Simple", "Detailed", "Quick", "Casual"],
    answer: "Detailed",
  },
  {
    id: 25,
    difficulty: "medium",
    question:
      "Choose the correct spelling: 'recieve', 'receive', 'recive', 'receeve'",
    options: ["recieve", "receive", "recive", "receeve"],
    answer: "receive",
  },
  {
    id: 26,
    difficulty: "medium",
    question: "Fill in the blank: 'She spoke to him _____ an hour.'",
    options: ["for", "since", "during", "while"],
    answer: "for",
  },
  {
    id: 27,
    difficulty: "medium",
    question: "What is the past participle of 'swim'?",
    options: ["swimmed", "swam", "swum", "swimming"],
    answer: "swum",
  },
  {
    id: 28,
    difficulty: "medium",
    question: "Choose the correct form: 'If I _____ you, I would apologize.'",
    options: ["am", "was", "were", "be"],
    answer: "were",
  },
  {
    id: 29,
    difficulty: "medium",
    question: "Which sentence is correctly punctuated?",
    options: [
      "Its a beautiful day, isn't it?",
      "It's a beautiful day, isn't it?",
      "Its a beautiful day isnt it?",
      "It's a beautiful day isnt it?",
    ],
    answer: "It's a beautiful day, isn't it?",
  },
  {
    id: 30,
    difficulty: "medium",
    question: "Fill in the blank: 'She is the woman _____ car was stolen.'",
    options: ["which", "who", "whose", "whom"],
    answer: "whose",
  },
  {
    id: 31,
    difficulty: "medium",
    question: "What is the antonym of 'generous'?",
    options: ["Selfish", "Kind", "Loving", "Caring"],
    answer: "Selfish",
  },
  {
    id: 32,
    difficulty: "medium",
    question: "Choose the correct word: 'The dog _____ all night.'",
    options: ["bark", "barks", "barked", "barking"],
    answer: "barked",
  },
  {
    id: 33,
    difficulty: "medium",
    question: "Fill in the blank: 'He hasn't called me _____ he left.'",
    options: ["since", "for", "by", "at"],
    answer: "since",
  },
  {
    id: 34,
    difficulty: "medium",
    question:
      "Choose the correct word: 'They decided to _____ their differences.'",
    options: ["reconcile", "recounsel", "reconcil", "rekonsile"],
    answer: "reconcile",
  },
  {
    id: 35,
    difficulty: "medium",
    question: "What is the correct plural form of 'analysis'?",
    options: ["analyses", "analysis", "analysises", "analys"],
    answer: "analyses",
  },
  {
    id: 36,
    difficulty: "medium",
    question:
      "Fill in the blank: 'She is not only talented _____ also hardworking.'",
    options: ["but", "and", "as", "nor"],
    answer: "but",
  },
  {
    id: 37,
    difficulty: "medium",
    question:
      "Which word is a conjunction? 'Although', 'Quickly', 'House', 'Under'",
    options: ["Although", "Quickly", "House", "Under"],
    answer: "Although",
  },
  {
    id: 38,
    difficulty: "medium",
    question: "Choose the correct form: 'I _____ him before.'",
    options: ["seen", "have seen", "saw", "see"],
    answer: "have seen",
  },
  {
    id: 39,
    difficulty: "medium",
    question: "Fill in the blank: 'He was accused _____ stealing the money.'",
    options: ["with", "of", "for", "by"],
    answer: "of",
  },
  {
    id: 40,
    difficulty: "medium",
    question:
      "Choose the correct word: 'She _____ to the store every Saturday.'",
    options: ["go", "goes", "went", "gone"],
    answer: "goes",
  },
  {
    id: 41,
    difficulty: "hard",
    question:
      "Identify the figure of speech in this sentence: 'The wind whispered through the trees.'",
    options: ["Metaphor", "Simile", "Personification", "Hyperbole"],
    answer: "Personification",
  },
  {
    id: 42,
    difficulty: "hard",
    question:
      "Choose the correct word: 'Despite the heavy rains, the match _____ on schedule.'",
    options: ["went", "goes", "gone", "was gone"],
    answer: "went",
  },
  {
    id: 43,
    difficulty: "hard",
    question: "What is the meaning of the word 'euphemism'?",
    options: [
      "A harsh term",
      "A polite term",
      "A term of endearment",
      "A term of insult",
    ],
    answer: "A polite term",
  },
  {
    id: 44,
    difficulty: "hard",
    question: "Fill in the blank: 'He _____ the book before the exam started.'",
    options: ["reads", "had read", "was reading", "is reading"],
    answer: "had read",
  },
  {
    id: 45,
    difficulty: "hard",
    question: "Which sentence uses the subjunctive mood correctly?",
    options: [
      "If I was you, I would apologize.",
      "If I am you, I would apologize.",
      "If I were you, I would apologize.",
      "If I be you, I would apologize.",
    ],
    answer: "If I were you, I would apologize.",
  },
  {
    id: 46,
    difficulty: "hard",
    question:
      "Identify the error in the following sentence: 'Each of the students have finished their assignment.'",
    options: ["Each of the students", "have", "finished", "their assignment"],
    answer: "have",
  },
  {
    id: 47,
    difficulty: "hard",
    question:
      "Choose the correct form: 'It is important that she _____ at the meeting.'",
    options: ["is", "be", "was", "has been"],
    answer: "be",
  },
  {
    id: 48,
    difficulty: "hard",
    question: "What is the meaning of the idiom 'burn the midnight oil'?",
    options: [
      "To burn something late at night",
      "To work late into the night",
      "To sleep early",
      "To wake up early",
    ],
    answer: "To work late into the night",
  },
  {
    id: 49,
    difficulty: "hard",
    question:
      "Identify the main clause in this sentence: 'Although it was raining, we went for a walk.'",
    options: [
      "Although it was raining",
      "it was raining",
      "we went for a walk",
      "went for a walk",
    ],
    answer: "we went for a walk",
  },
  {
    id: 50,
    difficulty: "hard",
    question:
      "Choose the correct sentence: 'She suggested that he study harder.', 'She suggested that he studies harder.', 'She suggested that he studied harder.', 'She suggested that he had studied harder.'",
    options: [
      "She suggested that he study harder.",
      "She suggested that he studies harder.",
      "She suggested that he studied harder.",
      "She suggested that he had studied harder.",
    ],
    answer: "She suggested that he study harder.",
  },
  {
    id: 51,
    difficulty: "hard",
    question: "What is the gerund form of the verb 'to swim'?",
    options: ["swimming", "swim", "swam", "swum"],
    answer: "swimming",
  },
  {
    id: 52,
    difficulty: "hard",
    question:
      "Identify the type of clause in this sentence: 'The book that I borrowed was fascinating.'",
    options: [
      "Independent clause",
      "Dependent clause",
      "Relative clause",
      "Noun clause",
    ],
    answer: "Relative clause",
  },
  {
    id: 53,
    difficulty: "hard",
    question: "Which sentence is written in the passive voice?",
    options: [
      "The manager approved the project.",
      "The project was approved by the manager.",
      "The manager is approving the project.",
      "The manager will approve the project.",
    ],
    answer: "The project was approved by the manager.",
  },
  {
    id: 54,
    difficulty: "hard",
    question:
      "Choose the correct sentence: 'Neither of them is available.', 'Neither of them are available.', 'Neither of them were available.', 'Neither of them have been available.'",
    options: [
      "Neither of them is available.",
      "Neither of them are available.",
      "Neither of them were available.",
      "Neither of them have been available.",
    ],
    answer: "Neither of them is available.",
  },
  {
    id: 55,
    difficulty: "hard",
    question: "What is the meaning of the word 'ambiguous'?",
    options: [
      "Clear and precise",
      "Doubtful or uncertain",
      "Strong and firm",
      "Weak and feeble",
    ],
    answer: "Doubtful or uncertain",
  },
  {
    id: 56,
    difficulty: "hard",
    question: "Fill in the blank: 'He acts _____ he were the boss.'",
    options: ["like", "as if", "as", "as though"],
    answer: "as if",
  },
  {
    id: 57,
    difficulty: "hard",
    question:
      "Choose the correct word: 'Her performance was _____ better than expected.'",
    options: ["far", "much", "many", "few"],
    answer: "much",
  },
  {
    id: 58,
    difficulty: "hard",
    question:
      "Identify the main verb in this sentence: 'She has been waiting for the bus for over an hour.'",
    options: ["has", "been", "waiting", "for"],
    answer: "waiting",
  },
  {
    id: 59,
    difficulty: "hard",
    question: "Which of the following sentences is grammatically correct?",
    options: [
      "He don't like coffee.",
      "He doesn't likes coffee.",
      "He doesn't like coffee.",
      "He not like coffee.",
    ],
    answer: "He doesn't like coffee.",
  },
  {
    id: 60,
    difficulty: "hard",
    question: "Choose the correct form: 'It's high time we _____ leaving.'",
    options: ["start", "started", "will start", "have started"],
    answer: "started",
  },
];

export const physics = [
  {
    id: 1,
    difficulty: "easy",
    question: "What is the SI unit of force?",
    options: ["Newton", "Joule", "Watt", "Pascal"],
    answer: "Newton",
  },
  {
    id: 2,
    difficulty: "easy",
    question: "What is the speed of light in a vacuum?",
    options: ["3 × 10^8 m/s", "3 × 10^6 m/s", "3 × 10^4 m/s", "3 × 10^2 m/s"],
    answer: "3 × 10^8 m/s",
  },
  {
    id: 3,
    difficulty: "easy",
    question: "What is the formula for kinetic energy?",
    options: ["1/2 mv^2", "mv^2", "mgh", "1/2 mgh"],
    answer: "1/2 mv^2",
  },
  {
    id: 4,
    difficulty: "easy",
    question: "What is the SI unit of electric current?",
    options: ["Ampere", "Volt", "Ohm", "Coulomb"],
    answer: "Ampere",
  },
  {
    id: 5,
    difficulty: "easy",
    question: "What is the acceleration due to gravity on Earth?",
    options: ["9.8 m/s^2", "8.9 m/s^2", "10 m/s^2", "9.0 m/s^2"],
    answer: "9.8 m/s^2",
  },
  {
    id: 6,
    difficulty: "easy",
    question:
      "What is the primary source of energy for the Earth's climate system?",
    options: ["The Sun", "The Moon", "Earth's core", "Stars"],
    answer: "The Sun",
  },
  {
    id: 7,
    difficulty: "easy",
    question: "What is the formula for Ohm's Law?",
    options: ["V = IR", "P = IV", "F = ma", "E = mc^2"],
    answer: "V = IR",
  },
  {
    id: 8,
    difficulty: "easy",
    question: "What is the SI unit of power?",
    options: ["Watt", "Joule", "Newton", "Volt"],
    answer: "Watt",
  },
  {
    id: 9,
    difficulty: "easy",
    question: "What is the atomic number of Hydrogen?",
    options: ["1", "2", "3", "4"],
    answer: "1",
  },
  {
    id: 10,
    difficulty: "easy",
    question:
      "What is the process of splitting a large atomic nucleus into smaller nuclei called?",
    options: ["Fission", "Fusion", "Decay", "Ionization"],
    answer: "Fission",
  },
  {
    id: 11,
    difficulty: "easy",
    question: "What is the frequency of a wave if its period is 0.1 seconds?",
    options: ["10 Hz", "0.1 Hz", "100 Hz", "1 Hz"],
    answer: "10 Hz",
  },
  {
    id: 12,
    difficulty: "easy",
    question: "What is the relationship between mass and weight?",
    options: [
      "Weight is mass times gravity",
      "Weight is mass divided by gravity",
      "Weight is mass plus gravity",
      "Weight is mass minus gravity",
    ],
    answer: "Weight is mass times gravity",
  },
  {
    id: 13,
    difficulty: "easy",
    question: "What is the formula for potential energy?",
    options: ["mgh", "1/2 mv^2", "mg", "gh"],
    answer: "mgh",
  },
  {
    id: 14,
    difficulty: "easy",
    question: "What is the unit of frequency?",
    options: ["Hertz", "Newton", "Pascal", "Joule"],
    answer: "Hertz",
  },
  {
    id: 15,
    difficulty: "easy",
    question: "What is the charge of an electron?",
    options: ["-1", "+1", "0", "+2"],
    answer: "-1",
  },
  {
    id: 16,
    difficulty: "easy",
    question:
      "What is the name of the force that opposes the motion of objects through the air?",
    options: ["Air resistance", "Gravity", "Normal force", "Tension"],
    answer: "Air resistance",
  },
  {
    id: 17,
    difficulty: "easy",
    question: "What is the formula for calculating density?",
    options: ["mass/volume", "mass × volume", "volume/mass", "mass + volume"],
    answer: "mass/volume",
  },
  {
    id: 18,
    difficulty: "easy",
    question:
      "What is the name of the phenomenon where light bends as it passes from one medium to another?",
    options: ["Refraction", "Reflection", "Diffraction", "Absorption"],
    answer: "Refraction",
  },
  {
    id: 19,
    difficulty: "easy",
    question:
      "What is the term for the number of protons in the nucleus of an atom?",
    options: ["Atomic number", "Mass number", "Isotope", "Ion"],
    answer: "Atomic number",
  },
  {
    id: 20,
    difficulty: "easy",
    question:
      "Which law states that for every action, there is an equal and opposite reaction?",
    options: [
      "Newton's Third Law",
      "Newton's First Law",
      "Newton's Second Law",
      "Law of Gravitation",
    ],
    answer: "Newton's Third Law",
  },
  {
    id: 21,
    difficulty: "medium",
    question:
      "What is the formula for calculating work done when a force is applied to an object?",
    options: [
      "Force × Distance",
      "Mass × Acceleration",
      "Force × Time",
      "Mass × Velocity",
    ],
    answer: "Force × Distance",
  },
  {
    id: 22,
    difficulty: "medium",
    question: "Which of the following particles has no charge?",
    options: ["Neutron", "Proton", "Electron", "Positron"],
    answer: "Neutron",
  },
  {
    id: 23,
    difficulty: "medium",
    question: "What is the unit of the magnetic field strength?",
    options: ["Tesla", "Newton", "Joule", "Pascal"],
    answer: "Tesla",
  },
  {
    id: 24,
    difficulty: "medium",
    question: "What is the principle behind a hydraulic lift?",
    options: [
      "Pascal's Principle",
      "Archimedes' Principle",
      "Bernoulli's Principle",
      "Newton's First Law",
    ],
    answer: "Pascal's Principle",
  },
  {
    id: 25,
    difficulty: "medium",
    question:
      "What is the term for the force that acts on objects in a circular path and is directed toward the center?",
    options: [
      "Centripetal Force",
      "Centrifugal Force",
      "Gravitational Force",
      "Frictional Force",
    ],
    answer: "Centripetal Force",
  },
  {
    id: 26,
    difficulty: "medium",
    question: "Which of the following is a scalar quantity?",
    options: ["Speed", "Velocity", "Force", "Acceleration"],
    answer: "Speed",
  },
  {
    id: 27,
    difficulty: "medium",
    question:
      "What is the formula for calculating the period of a simple pendulum?",
    options: ["2π√(L/g)", "2π√(g/L)", "π√(L/g)", "π√(g/L)"],
    answer: "2π√(L/g)",
  },
  {
    id: 28,
    difficulty: "medium",
    question:
      "Which law states that the pressure of a gas is inversely proportional to its volume at constant temperature?",
    options: [
      "Boyle's Law",
      "Charles' Law",
      "Gay-Lussac's Law",
      "Avogadro's Law",
    ],
    answer: "Boyle's Law",
  },
  {
    id: 29,
    difficulty: "medium",
    question:
      "What is the formula for calculating the electric potential energy between two point charges?",
    options: ["kQ₁Q₂/r", "kQ₁/r²", "kQ₂/r", "kQ₁Q₂/r²"],
    answer: "kQ₁Q₂/r",
  },
  {
    id: 30,
    difficulty: "medium",
    question: "What is the term for the rate of change of velocity?",
    options: ["Acceleration", "Speed", "Displacement", "Force"],
    answer: "Acceleration",
  },
  {
    id: 31,
    difficulty: "medium",
    question: "What is the formula for calculating momentum?",
    options: [
      "mass × velocity",
      "mass × acceleration",
      "force × distance",
      "force × time",
    ],
    answer: "mass × velocity",
  },
  {
    id: 32,
    difficulty: "medium",
    question: "Which of the following is the correct definition of power?",
    options: [
      "Work done per unit time",
      "Force applied per unit time",
      "Energy stored per unit time",
      "Velocity per unit time",
    ],
    answer: "Work done per unit time",
  },
  {
    id: 33,
    difficulty: "medium",
    question: "Which type of wave is a sound wave?",
    options: ["Longitudinal", "Transverse", "Electromagnetic", "Surface"],
    answer: "Longitudinal",
  },
  {
    id: 34,
    difficulty: "medium",
    question:
      "What is the term for the measure of a material's resistance to deformation?",
    options: ["Elasticity", "Viscosity", "Density", "Conductivity"],
    answer: "Elasticity",
  },
  {
    id: 35,
    difficulty: "medium",
    question: "What is the unit of electric resistance?",
    options: ["Ohm", "Volt", "Ampere", "Coulomb"],
    answer: "Ohm",
  },
  {
    id: 36,
    difficulty: "medium",
    question:
      "Which of the following particles is a fundamental building block of matter?",
    options: ["Quark", "Photon", "Neutrino", "Gluon"],
    answer: "Quark",
  },
  {
    id: 37,
    difficulty: "medium",
    question: "What is the term for the amount of space an object occupies?",
    options: ["Volume", "Mass", "Density", "Area"],
    answer: "Volume",
  },
  {
    id: 38,
    difficulty: "medium",
    question:
      "Which of the following quantities is conserved in an elastic collision?",
    options: [
      "Kinetic energy and momentum",
      "Kinetic energy only",
      "Momentum only",
      "Neither kinetic energy nor momentum",
    ],
    answer: "Kinetic energy and momentum",
  },
  {
    id: 39,
    difficulty: "medium",
    question:
      "What is the formula for calculating the gravitational force between two masses?",
    options: ["Gm₁m₂/r²", "Gm₁m₂/r", "Gm₁/r²", "Gm₂/r"],
    answer: "Gm₁m₂/r²",
  },
  {
    id: 40,
    difficulty: "medium",
    question:
      "What is the term for the bending of light as it passes around the edge of an object?",
    options: ["Diffraction", "Reflection", "Refraction", "Dispersion"],
    answer: "Diffraction",
  },
  {
    id: 41,
    difficulty: "hard",
    question:
      "What is the relativistic formula for the total energy of a particle?",
    options: [
      "E = mc^2",
      "E = (mc^2)/√(1 - v^2/c^2)",
      "E = mv^2",
      "E = mc^2 + 1/2mv^2",
    ],
    answer: "E = (mc^2)/√(1 - v^2/c^2)",
  },
  {
    id: 42,
    difficulty: "hard",
    question: "What is the Heisenberg Uncertainty Principle?",
    options: ["ΔxΔp ≥ h/4π", "ΔxΔp ≥ h/2π", "ΔxΔp ≥ h/π", "ΔxΔp ≥ h"],
    answer: "ΔxΔp ≥ h/4π",
  },
  {
    id: 43,
    difficulty: "hard",
    question: "What is the value of the gravitational constant (G)?",
    options: [
      "6.67 × 10^-11 N·m²/kg²",
      "9.81 N/kg",
      "3.00 × 10^8 m/s",
      "1.60 × 10^-19 C",
    ],
    answer: "6.67 × 10^-11 N·m²/kg²",
  },
  {
    id: 44,
    difficulty: "hard",
    question: "What is the formula for the de Broglie wavelength?",
    options: ["λ = h/p", "λ = h/E", "λ = E/p", "λ = p/h"],
    answer: "λ = h/p",
  },
  {
    id: 45,
    difficulty: "hard",
    question: "Which fundamental force is the weakest?",
    options: [
      "Gravitational",
      "Electromagnetic",
      "Strong Nuclear",
      "Weak Nuclear",
    ],
    answer: "Gravitational",
  },
  {
    id: 46,
    difficulty: "hard",
    question:
      "In quantum mechanics, what does the Schrödinger equation describe?",
    options: [
      "The time evolution of a quantum system's wave function",
      "The trajectory of a particle",
      "The energy levels of electrons in an atom",
      "The speed of light in a vacuum",
    ],
    answer: "The time evolution of a quantum system's wave function",
  },
  {
    id: 47,
    difficulty: "hard",
    question: "What is the Pauli Exclusion Principle?",
    options: [
      "No two fermions can occupy the same quantum state simultaneously",
      "Electrons can only exist in discrete energy levels",
      "Energy is quantized",
      "Light has both particle and wave properties",
    ],
    answer: "No two fermions can occupy the same quantum state simultaneously",
  },
  {
    id: 48,
    difficulty: "hard",
    question:
      "What is the formula for calculating the escape velocity from a planet?",
    options: ["√(2GM/R)", "√(GM/R^2)", "√(GMR)", "√(2GMR^2)"],
    answer: "√(2GM/R)",
  },
  {
    id: 49,
    difficulty: "hard",
    question: "What phenomenon explains why the sky is blue?",
    options: [
      "Rayleigh Scattering",
      "Mie Scattering",
      "Compton Scattering",
      "Diffraction",
    ],
    answer: "Rayleigh Scattering",
  },
  {
    id: 50,
    difficulty: "hard",
    question: "What is the main component of a neutron star?",
    options: ["Neutrons", "Protons", "Electrons", "Quarks"],
    answer: "Neutrons",
  },
  {
    id: 51,
    difficulty: "hard",
    question: "What is the primary cause of the greenhouse effect?",
    options: [
      "Infrared absorption by atmospheric gases",
      "Ultraviolet absorption by ozone",
      "Visible light absorption by clouds",
      "Reflection of sunlight by the Earth's surface",
    ],
    answer: "Infrared absorption by atmospheric gases",
  },
  {
    id: 52,
    difficulty: "hard",
    question:
      "What is the formula for the Lorentz factor in special relativity?",
    options: [
      "γ = 1/√(1 - v^2/c^2)",
      "γ = 1/√(1 + v^2/c^2)",
      "γ = √(1 - v^2/c^2)",
      "γ = √(1 + v^2/c^2)",
    ],
    answer: "γ = 1/√(1 - v^2/c^2)",
  },
  {
    id: 53,
    difficulty: "hard",
    question: "What is the formula for the energy of a photon?",
    options: ["E = hf", "E = hv", "E = hλ", "E = hc/λ"],
    answer: "E = hf",
  },
  {
    id: 54,
    difficulty: "hard",
    question: "What does Maxwell's first equation (Gauss's Law) state?",
    options: [
      "The electric flux through any closed surface is proportional to the enclosed electric charge",
      "The magnetic flux through any closed surface is proportional to the enclosed magnetic charge",
      "The electric flux through any open surface is proportional to the enclosed electric charge",
      "The magnetic flux through any open surface is proportional to the enclosed magnetic charge",
    ],
    answer:
      "The electric flux through any closed surface is proportional to the enclosed electric charge",
  },
  {
    id: 55,
    difficulty: "hard",
    question:
      "What is the energy equivalent of 1 atomic mass unit (amu) in MeV?",
    options: ["931.5 MeV", "1 MeV", "9.31 MeV", "9315 MeV"],
    answer: "931.5 MeV",
  },
  {
    id: 56,
    difficulty: "hard",
    question: "What is the principle of superposition in wave theory?",
    options: [
      "When two or more waves overlap, the resultant displacement is the sum of the displacements of the individual waves",
      "When two or more waves overlap, the resultant frequency is the sum of the frequencies of the individual waves",
      "When two or more waves overlap, the resultant amplitude is the sum of the amplitudes of the individual waves",
      "When two or more waves overlap, the resultant wavelength is the sum of the wavelengths of the individual waves",
    ],
    answer:
      "When two or more waves overlap, the resultant displacement is the sum of the displacements of the individual waves",
  },
  {
    id: 57,
    difficulty: "hard",
    question:
      "What is the formula for calculating the angular momentum of a particle?",
    options: ["L = r × p", "L = r × mv", "L = Iω", "L = p × r"],
    answer: "L = r × p",
  },
  {
    id: 58,
    difficulty: "hard",
    question:
      "What is the term for the theoretical point where a black hole's gravitational pull becomes infinite?",
    options: [
      "Singularity",
      "Event Horizon",
      "Schwarzschild Radius",
      "Photon Sphere",
    ],
    answer: "Singularity",
  },
  {
    id: 59,
    difficulty: "hard",
    question: "What is the principle of equivalence in general relativity?",
    options: [
      "Gravitational mass is equivalent to inertial mass",
      "Energy is equivalent to mass",
      "Gravitational force is equivalent to centrifugal force",
      "The speed of light is equivalent to the speed of sound",
    ],
    answer: "Gravitational mass is equivalent to inertial mass",
  },
  {
    id: 60,
    difficulty: "hard",
    question: "What is the Stefan-Boltzmann law?",
    options: [
      "The total energy radiated per unit surface area of a black body is proportional to the fourth power of its absolute temperature",
      "The total energy radiated per unit surface area of a black body is proportional to the square of its absolute temperature",
      "The total energy radiated per unit surface area of a black body is proportional to the cube of its absolute temperature",
      "The total energy radiated per unit surface area of a black body is proportional to its absolute temperature",
    ],
    answer:
      "The total energy radiated per unit surface area of a black body is proportional to the fourth power of its absolute temperature",
  },
];

export const chemistry = [
  {
    id: 61,
    difficulty: "easy",
    question: "What is the chemical symbol for water?",
    options: ["H2O", "O2", "H2", "OH"],
    answer: "H2O",
  },
  {
    id: 62,
    difficulty: "easy",
    question: "What is the pH of a neutral solution?",
    options: ["7", "0", "14", "1"],
    answer: "7",
  },
  {
    id: 63,
    difficulty: "easy",
    question: "What is the atomic number of carbon?",
    options: ["6", "12", "14", "8"],
    answer: "6",
  },
  {
    id: 64,
    difficulty: "easy",
    question: "Which element has the chemical symbol 'O'?",
    options: ["Oxygen", "Osmium", "Oganesson", "Osmolite"],
    answer: "Oxygen",
  },
  {
    id: 65,
    difficulty: "easy",
    question: "What is the most abundant gas in the Earth's atmosphere?",
    options: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"],
    answer: "Nitrogen",
  },
  {
    id: 66,
    difficulty: "easy",
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "KCl", "CaCl2", "Na2CO3"],
    answer: "NaCl",
  },
  {
    id: 67,
    difficulty: "easy",
    question:
      "Which type of bond involves the sharing of electron pairs between atoms?",
    options: [
      "Covalent bond",
      "Ionic bond",
      "Hydrogen bond",
      "Van der Waals force",
    ],
    answer: "Covalent bond",
  },
  {
    id: 68,
    difficulty: "easy",
    question: "What is the common name for dihydrogen monoxide?",
    options: ["Water", "Hydrogen Peroxide", "Methane", "Carbon Dioxide"],
    answer: "Water",
  },
  {
    id: 69,
    difficulty: "easy",
    question: "Which element is a noble gas?",
    options: ["Neon", "Oxygen", "Nitrogen", "Carbon"],
    answer: "Neon",
  },
  {
    id: 70,
    difficulty: "easy",
    question: "What is the charge of an electron?",
    options: ["-1", "+1", "0", "+2"],
    answer: "-1",
  },
  {
    id: 71,
    difficulty: "easy",
    question: "Which element has the highest atomic number?",
    options: ["Oganesson", "Uranium", "Plutonium", "Hydrogen"],
    answer: "Oganesson",
  },
  {
    id: 72,
    difficulty: "easy",
    question: "What is the chemical symbol for gold?",
    options: ["Au", "Ag", "Pb", "Hg"],
    answer: "Au",
  },
  {
    id: 73,
    difficulty: "easy",
    question: "Which of the following is a chemical reaction?",
    options: [
      "Rusting of iron",
      "Melting of ice",
      "Boiling of water",
      "Dissolving sugar in water",
    ],
    answer: "Rusting of iron",
  },
  {
    id: 74,
    difficulty: "easy",
    question: "Which element has the chemical symbol 'Fe'?",
    options: ["Iron", "Fluorine", "Francium", "Fermium"],
    answer: "Iron",
  },
  {
    id: 75,
    difficulty: "easy",
    question: "What is the atomic number of hydrogen?",
    options: ["1", "2", "3", "4"],
    answer: "1",
  },
  {
    id: 76,
    difficulty: "easy",
    question: "Which of the following is an alkaline earth metal?",
    options: ["Calcium", "Sodium", "Potassium", "Chlorine"],
    answer: "Calcium",
  },
  {
    id: 77,
    difficulty: "easy",
    question: "What is the main component of natural gas?",
    options: ["Methane", "Ethane", "Propane", "Butane"],
    answer: "Methane",
  },
  {
    id: 78,
    difficulty: "easy",
    question: "What is the chemical symbol for sodium?",
    options: ["Na", "S", "N", "K"],
    answer: "Na",
  },
  {
    id: 79,
    difficulty: "easy",
    question: "Which of the following is an organic compound?",
    options: ["Methane", "Water", "Sodium Chloride", "Ammonia"],
    answer: "Methane",
  },
  {
    id: 80,
    difficulty: "easy",
    question: "What is the pH of a basic solution?",
    options: ["Greater than 7", "Less than 7", "Equal to 7", "Equal to 0"],
    answer: "Greater than 7",
  },
  {
    id: 81,
    difficulty: "medium",
    question: "What is the electron configuration of a sodium atom?",
    options: [
      "1s² 2s² 2p⁶ 3s¹",
      "1s² 2s² 2p⁵ 3s²",
      "1s² 2s² 2p⁶",
      "1s² 2s² 2p⁶ 3p¹",
    ],
    answer: "1s² 2s² 2p⁶ 3s¹",
  },
  {
    id: 82,
    difficulty: "medium",
    question: "What is the molecular geometry of carbon dioxide (CO2)?",
    options: ["Linear", "Bent", "Trigonal Planar", "Tetrahedral"],
    answer: "Linear",
  },
  {
    id: 83,
    difficulty: "medium",
    question: "Which of the following is a weak acid?",
    options: [
      "Acetic Acid",
      "Hydrochloric Acid",
      "Sulfuric Acid",
      "Nitric Acid",
    ],
    answer: "Acetic Acid",
  },
  {
    id: 84,
    difficulty: "medium",
    question: "What is the chemical formula for ammonium sulfate?",
    options: ["(NH4)2SO4", "NH4SO4", "NH3SO4", "NH4S"],
    answer: "(NH4)2SO4",
  },
  {
    id: 85,
    difficulty: "medium",
    question:
      "Which type of hybridization is present in the methane (CH4) molecule?",
    options: ["sp3", "sp2", "sp", "dsp2"],
    answer: "sp3",
  },
  {
    id: 86,
    difficulty: "medium",
    question:
      "What is the oxidation state of chromium in the dichromate ion (Cr2O7^2-)?",
    options: ["+6", "+3", "+2", "+7"],
    answer: "+6",
  },
  {
    id: 87,
    difficulty: "medium",
    question:
      "Which law states that the pressure of a gas is directly proportional to its temperature at constant volume?",
    options: [
      "Gay-Lussac's Law",
      "Boyle's Law",
      "Charles's Law",
      "Avogadro's Law",
    ],
    answer: "Gay-Lussac's Law",
  },
  {
    id: 88,
    difficulty: "medium",
    question:
      "What is the name of the compound with the chemical formula Na2CO3?",
    options: [
      "Sodium Carbonate",
      "Sodium Bicarbonate",
      "Sodium Chloride",
      "Sodium Sulfate",
    ],
    answer: "Sodium Carbonate",
  },
  {
    id: 89,
    difficulty: "medium",
    question: "What is the main product when sodium reacts with water?",
    options: [
      "Sodium Hydroxide",
      "Sodium Oxide",
      "Sodium Chloride",
      "Sodium Nitrate",
    ],
    answer: "Sodium Hydroxide",
  },
  {
    id: 90,
    difficulty: "medium",
    question: "What is the empirical formula of glucose (C6H12O6)?",
    options: ["CH2O", "C2H4O2", "CHO", "C6H12O6"],
    answer: "CH2O",
  },
  {
    id: 91,
    difficulty: "medium",
    question: "Which of the following elements is a halogen?",
    options: ["Fluorine", "Oxygen", "Nitrogen", "Sulfur"],
    answer: "Fluorine",
  },
  {
    id: 92,
    difficulty: "medium",
    question: "Which ion is responsible for the acidic properties of an acid?",
    options: [
      "Hydrogen Ion (H+)",
      "Hydroxide Ion (OH-)",
      "Sulfate Ion (SO4^2-)",
      "Nitrate Ion (NO3-)",
    ],
    answer: "Hydrogen Ion (H+)",
  },
  {
    id: 93,
    difficulty: "medium",
    question: "Which of the following is the best conductor of electricity?",
    options: ["Silver", "Copper", "Aluminum", "Iron"],
    answer: "Silver",
  },
  {
    id: 94,
    difficulty: "medium",
    question: "What is the main component of limestone?",
    options: [
      "Calcium Carbonate",
      "Calcium Sulfate",
      "Calcium Hydroxide",
      "Calcium Chloride",
    ],
    answer: "Calcium Carbonate",
  },
  {
    id: 95,
    difficulty: "medium",
    question: "What is the common name for sodium bicarbonate?",
    options: ["Baking Soda", "Table Salt", "Epsom Salt", "Bleach"],
    answer: "Baking Soda",
  },
  {
    id: 96,
    difficulty: "medium",
    question:
      "Which of the following processes involves the gain of electrons?",
    options: ["Reduction", "Oxidation", "Electrolysis", "Precipitation"],
    answer: "Reduction",
  },
  {
    id: 97,
    difficulty: "medium",
    question:
      "What is the term for the amount of substance containing the same number of entities as there are atoms in 12 grams of carbon-12?",
    options: ["Mole", "Gram", "Kilogram", "Liter"],
    answer: "Mole",
  },
  {
    id: 98,
    difficulty: "medium",
    question: "What is the chemical name for rust?",
    options: [
      "Iron(III) Oxide",
      "Iron(II) Oxide",
      "Iron(II) Chloride",
      "Iron(III) Chloride",
    ],
    answer: "Iron(III) Oxide",
  },
  {
    id: 99,
    difficulty: "medium",
    question: "Which of the following is an example of an alloy?",
    options: ["Steel", "Iron", "Aluminum", "Copper"],
    answer: "Steel",
  },
  {
    id: 100,
    difficulty: "medium",
    question:
      "What type of bond is formed between the carbon and hydrogen atoms in methane (CH4)?",
    options: [
      "Single Covalent Bond",
      "Double Covalent Bond",
      "Ionic Bond",
      "Metallic Bond",
    ],
    answer: "Single Covalent Bond",
  },
  {
    id: 101,
    difficulty: "hard",
    question: "What is the electron configuration of the Fe3+ ion?",
    options: ["[Ar] 3d5", "[Ar] 3d6", "[Ar] 4s2 3d3", "[Ar] 4s1 3d5"],
    answer: "[Ar] 3d5",
  },
  {
    id: 102,
    difficulty: "hard",
    question: "What is the bond angle in a molecule with sp2 hybridization?",
    options: ["120°", "109.5°", "180°", "90°"],
    answer: "120°",
  },
  {
    id: 103,
    difficulty: "hard",
    question:
      "What is the chemical formula for the compound formed between aluminum and sulfate ions?",
    options: ["Al2(SO4)3", "Al(SO4)3", "Al2SO4", "AlSO4"],
    answer: "Al2(SO4)3",
  },
  {
    id: 104,
    difficulty: "hard",
    question: "What is the hybridization of the central atom in SF6?",
    options: ["sp3d2", "sp3", "sp3d", "sp2"],
    answer: "sp3d2",
  },
  {
    id: 105,
    difficulty: "hard",
    question:
      "What is the name of the process in which a liquid changes into a gas below its boiling point?",
    options: ["Evaporation", "Sublimation", "Condensation", "Deposition"],
    answer: "Evaporation",
  },
  {
    id: 106,
    difficulty: "hard",
    question: "Which type of intermolecular force is the strongest?",
    options: [
      "Hydrogen Bonding",
      "Dipole-Dipole Interaction",
      "London Dispersion Forces",
      "Ionic Bond",
    ],
    answer: "Hydrogen Bonding",
  },
  {
    id: 107,
    difficulty: "hard",
    question:
      "Which of the following compounds is an example of a chelating agent?",
    options: ["EDTA", "H2O", "NaCl", "CO2"],
    answer: "EDTA",
  },
  {
    id: 108,
    difficulty: "hard",
    question:
      "What is the primary structural feature of an alpha-helix in proteins?",
    options: [
      "Hydrogen bonds between backbone atoms",
      "Hydrogen bonds between side chain atoms",
      "Disulfide bridges",
      "Ionic bonds",
    ],
    answer: "Hydrogen bonds between backbone atoms",
  },
  {
    id: 109,
    difficulty: "hard",
    question:
      "What is the main distinction between an exothermic and endothermic reaction?",
    options: [
      "Exothermic reactions release heat, endothermic reactions absorb heat",
      "Exothermic reactions absorb heat, endothermic reactions release heat",
      "Exothermic reactions are fast, endothermic reactions are slow",
      "Exothermic reactions are slow, endothermic reactions are fast",
    ],
    answer:
      "Exothermic reactions release heat, endothermic reactions absorb heat",
  },
  {
    id: 110,
    difficulty: "hard",
    question:
      "What is the standard Gibbs free energy change (ΔG°) for a reaction at equilibrium?",
    options: ["0", "Positive", "Negative", "Undefined"],
    answer: "0",
  },
  {
    id: 111,
    difficulty: "hard",
    question: "What is the IUPAC name for the compound CH3CH2COOH?",
    options: [
      "Propanoic Acid",
      "Ethanoic Acid",
      "Butanoic Acid",
      "Methanoic Acid",
    ],
    answer: "Propanoic Acid",
  },
  {
    id: 112,
    difficulty: "hard",
    question: "What type of isomerism is exhibited by 1-butene and 2-butene?",
    options: [
      "Positional Isomerism",
      "Geometric Isomerism",
      "Optical Isomerism",
      "Functional Group Isomerism",
    ],
    answer: "Positional Isomerism",
  },
  {
    id: 113,
    difficulty: "hard",
    question: "What is the product of the complete combustion of hydrocarbons?",
    options: ["CO2 and H2O", "CO and H2O", "CO and H2", "CO2 and H2"],
    answer: "CO2 and H2O",
  },
  {
    id: 114,
    difficulty: "hard",
    question:
      "Which reagent can be used to oxidize a primary alcohol to an aldehyde?",
    options: ["PCC (Pyridinium Chlorochromate)", "KMnO4", "H2SO4", "NaBH4"],
    answer: "PCC (Pyridinium Chlorochromate)",
  },
  {
    id: 115,
    difficulty: "hard",
    question: "What is the main purpose of a catalyst in a chemical reaction?",
    options: [
      "To increase the reaction rate",
      "To decrease the reaction rate",
      "To change the equilibrium position",
      "To provide reactants",
    ],
    answer: "To increase the reaction rate",
  },
  {
    id: 116,
    difficulty: "hard",
    question:
      "What is the molarity of a solution containing 5 moles of solute in 2 liters of solution?",
    options: ["2.5 M", "0.5 M", "10 M", "5 M"],
    answer: "2.5 M",
  },
  {
    id: 117,
    difficulty: "hard",
    question: "What is the general formula for an alkane?",
    options: ["CnH2n+2", "CnH2n", "CnH2n-2", "CnH2n+1"],
    answer: "CnH2n+2",
  },
  {
    id: 118,
    difficulty: "hard",
    question:
      "Which of the following ions has a noble gas electron configuration?",
    options: ["Na+", "Cl-", "Mg2+", "All of the above"],
    answer: "All of the above",
  },
  {
    id: 119,
    difficulty: "hard",
    question: "What is the pH of a 0.01 M HCl solution?",
    options: ["2", "12", "7", "4"],
    answer: "2",
  },
  {
    id: 120,
    difficulty: "hard",
    question: "Which quantum number describes the shape of an orbital?",
    options: [
      "Azimuthal quantum number (l)",
      "Principal quantum number (n)",
      "Magnetic quantum number (m)",
      "Spin quantum number (s)",
    ],
    answer: "Azimuthal quantum number (l)",
  },
];

export const englisMispellet = [
  {
    id: 1,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Recieve", "Receive", "Recive", "Receeve"],
    answer: "Receive",
  },
  {
    id: 2,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Definately", "Definitely", "Defanitely", "Definitley"],
    answer: "Definitely",
  },
  {
    id: 3,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Accommodate", "Acommodate", "Accomodate", "Acommodate"],
    answer: "Accommodate",
  },
  {
    id: 4,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Buisness", "Bussiness", "Business", "Busness"],
    answer: "Business",
  },
  {
    id: 5,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Managable", "Manageable", "Managible", "Managible"],
    answer: "Manageable",
  },
  {
    id: 6,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Enviroment", "Environement", "Enviornment", "Environment"],
    answer: "Environment",
  },
  {
    id: 7,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Publically", "Publicly", "Publikly", "Publicaly"],
    answer: "Publicly",
  },
  {
    id: 8,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Neccessary", "Necessary", "Necessay", "Necessery"],
    answer: "Necessary",
  },
  {
    id: 9,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Adress", "Address", "Adrees", "Adreess"],
    answer: "Address",
  },
  {
    id: 10,
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Febuary", "February", "Febraury", "Febraury"],
    answer: "February",
  },
  {
    id: 11,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Guarentee", "Guarantee", "Gaurantee", "Gaurantee"],
    answer: "Guarantee",
  },
  {
    id: 12,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Separate", "Seperate", "Seperete", "Separite"],
    answer: "Separate",
  },
  {
    id: 13,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Arguement", "Argument", "Arguemant", "Arguemant"],
    answer: "Argument",
  },
  {
    id: 14,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Independant", "Independent", "Indepandent", "Indepedent"],
    answer: "Independent",
  },
  {
    id: 15,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Mispell", "Misspell", "Mispel", "Misspel"],
    answer: "Misspell",
  },
  {
    id: 16,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Occurrance", "Occurrence", "Occurence", "Occurrance"],
    answer: "Occurrence",
  },
  {
    id: 17,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: [
      "Pronounciation",
      "Pronunciation",
      "Prononciation",
      "Pronunciaton",
    ],
    answer: "Pronunciation",
  },
  {
    id: 18,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Refered", "Referred", "Referrred", "Refered"],
    answer: "Referred",
  },
  {
    id: 19,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Harass", "Harrass", "Haras", "Harras"],
    answer: "Harass",
  },
  {
    id: 20,
    difficulty: "medium",
    question: "Which word is spelled correctly?",
    options: ["Bureaucracy", "Beauracracy", "Bureacracy", "Bureaurcracy"],
    answer: "Bureaucracy",
  },
  {
    id: 1,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Pharaoh", "Pharoah", "Pharao", "Pharoh"],
    answer: "Pharaoh",
  },
  {
    id: 2,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Supersede", "Supercede", "Superscede", "Superseed"],
    answer: "Supersede",
  },
  {
    id: 3,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Connoisseur", "Connoisuer", "Connoisseur", "Connoissur"],
    answer: "Connoisseur",
  },
  {
    id: 4,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Acquiesce", "Acquiese", "Acqueisce", "Acquiese"],
    answer: "Acquiesce",
  },
  {
    id: 5,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Handkerchief", "Handkercheif", "Handkercief", "Handkerchef"],
    answer: "Handkerchief",
  },
  {
    id: 6,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Onomatopoeia", "Onomatopoia", "Onomatopea", "Onomatopeia"],
    answer: "Onomatopoeia",
  },
  {
    id: 7,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Mnemonics", "Mnemomics", "Mnemnics", "Mneminics"],
    answer: "Mnemonics",
  },
  {
    id: 8,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Occasion", "Occassion", "Ocassion", "Occassion"],
    answer: "Occasion",
  },
  {
    id: 9,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Minuscule", "Miniscule", "Minuscule", "Minicule"],
    answer: "Minuscule",
  },
  {
    id: 10,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Ebullient", "Ebullant", "Ebulliant", "Ebulient"],
    answer: "Ebullient",
  },
  {
    id: 11,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Camaraderie", "Camaraderi", "Camaradery", "Cameraderie"],
    answer: "Camaraderie",
  },
  {
    id: 12,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Surreptitious", "Surrepticious", "Surreptious", "Surruptitious"],
    answer: "Surreptitious",
  },
  {
    id: 13,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Apocryphal", "Apocryfal", "Apocryphal", "Apocryful"],
    answer: "Apocryphal",
  },
  {
    id: 14,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Bougainvillea", "Bouganvillea", "Bougainvilea", "Bouganvilea"],
    answer: "Bougainvillea",
  },
  {
    id: 15,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: [
      "Ecclesiastical",
      "Ecclestiastical",
      "Eclesiastical",
      "Ecclesiasticel",
    ],
    answer: "Ecclesiastical",
  },
  {
    id: 16,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Sacrilegious", "Sacreligious", "Sacreligious", "Sacrelegious"],
    answer: "Sacrilegious",
  },
  {
    id: 17,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Synecdoche", "Sinecdoche", "Sinecdochy", "Synecdochy"],
    answer: "Synecdoche",
  },
  {
    id: 18,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: ["Rechauffe", "Rechaufé", "Rechauffé", "Rechaufè"],
    answer: "Rechauffé",
  },
  {
    id: 19,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: [
      "Sesquipedalian",
      "Sesquapedalian",
      "Sesquipadalian",
      "Sesquepedalian",
    ],
    answer: "Sesquipedalian",
  },
  {
    id: 20,
    difficulty: "hard",
    question: "Which word is spelled correctly?",
    options: [
      "Floccinaucinihilipilification",
      "Floccinaucinihilipilifacation",
      "Floccinaucinihilipilification",
      "Floccinaucinihilipilifacation",
    ],
    answer: "Floccinaucinihilipilification",
  },
];
